# Generated by Django 2.0.5 on 2018-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketupdate_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
