# Generated by Django 2.0.5 on 2018-11-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketupdate_model', '0002_auto_20181103_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Update'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Category'),
        ),
        migrations.AlterField(
            model_name='value',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Symbol'),
        ),
    ]
